### ISSUE TITLE
[Suggestion] Move health gui closer to hotbar such that it matches Beta 1.7.3 and older versions  

### ISSUE THREAD

**Issue by inboundbark** [SmushyTaco/Experience-Remover#1]
Beta 1.7.3:
![2021-07-02_22 56 56](https://user-images.githubusercontent.com/50455200/124327955-0113a800-db89-11eb-90b3-d4b97f900a1f.png)

1.17:
![image](https://user-images.githubusercontent.com/50455200/124327965-05d85c00-db89-11eb-9853-aca4e92cd5b8.png)

On the 1.17 image there is a slighter larger gap between the health and the hotbar.

**Comment by SmushyTaco** [comment]
I purposefully made it 1 pixel higher, if it wasn't it would touch the selected item hotbar box which I don't want. I won't be adding an option to lower the health gui.
