### ISSUE TITLE
[Suggestion] Config: "Remove Experience Costs"

### ISSUE THREAD

**Issue by MinerB4** [SmushyTaco/Experience-Remover#3]
With this enabled, the player will technically have an infinite amount of XP (or at least the highest amount allowed). They will still be able to use anvils, enchantment tables, and other modded items that use experience points/levels.
With this disabled, the player will technically have 0 XP. This effectively disables Enchantment Tables and Anvils again.

**Comment by SmushyTaco** [comment]
Not interested in implementing this
